# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 楽圜
subtitle:
description: 
author: Jane w. Gu
language:
- zh
- en
timezone: Asia/Shanghai
date: 2016

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.janeis.win/
#root:
permalink: :lang/:year-:month/:title/
permalink_defaults: 
  lang: zh
  year: 1993
  month: 08
  title: nice-to-meet-u

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
# auto_spacing: true # 中英文中自动空格
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false # 启动资源文件夹：大量外部资源
relative_link: false # 把链接改为相对地址
future: false # 不显示未来的文章
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized # 默认分类
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
# per_page: 6
# pagination_dir: page

index_generator:
  per_page: 1
  order_by: -date

archive_generator:
  per_page: 10  
  order_by: -date

tag_generator:
  per_page: 10

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Mr.white
#theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:Giina/Giina.github.io.git
  branch: master
  message: v2
