
# html lang
language: zh

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives
  Tags: /tags
  Categories: /categories

# Miscelaneous
# favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/Mr.white.css

# scripts loaded in the end of the body
scripts:
- /js/Mr.white.js

# color set
colors:
  highlight:#fbdd69